### PR TITLE
New PR for Maximilian 2.1 with JS and AudioWorklet

### PR DESCRIPTION
**Pull request by frantic0**
Summary:
Main changes to Web Audio build – transpiled javascript version of the library is included in this repository, for both Script Processor Nodes and Audio AudioWorklets. 

Other changes:

README -> README.md
src - now holds the C++ src, the C++ libs and the embindings.
js - holds ScriptProcessorNode (asm.js legacy) and audioWorklet (Wasm) dirs, each with it's own * makefile, build directory, shared libs, examples, and a python webserver script for convenience of testing.
cpp - holds C++ client code and project (basically the old stuff).

### CODE REVIEW

**Comment by micknoise** [comment]
Can you pull the latest version on your end first?
main.cpp
maximilianTest.xcodeproj/project.pbxproj
openFrameworks/ofxMaxim/libs/maximilian.cpp
openFrameworks/ofxMaxim/libs/maximilian.h
openFrameworks/ofxMaxim/src/ofxMaxim.h

**Comment by frantic0** [comment]
Pick it up again on Monday

**Comment by micknoise** [comment]
Great. It would be fantastic to do this today or tomorrow.

**Comment by frantic0** [comment]
> This release looks really fantastic as I would expect. In general everything seems to work as we require. The only thing I would recommend is that the read.me highlights the audioworklet work more specifically - so please consider moving the information on the audio workout examples to the first section under #basic examples and before the C++ information

Changed the README as requested, updated audioworklet examples, merged our fork to the upstream repo. @chriskiefer @micknoise could you please check if the cpp openFrameworks and cmd aren't broken with the merge?

**Pull request merged**
